import {
  HOST_URL_SYNC_CAPABILITY,
  NODE_NAME_SYNC_CAPABILITY,
  OUTBOX_ACK_CAPABILITY,
  SELF_UPDATE_CAPABILITY,
  SESSION_ACTIVITY_CAPABILITY,
  SESSION_CONFIG_CAPABILITY,
  SESSION_RETENTION_CAPABILITY,
} from "@fleet/protocol";

export const NODE_CAPABILITIES = [
  "copilot-acp",
  "host-yolo",
  HOST_URL_SYNC_CAPABILITY,
  SELF_UPDATE_CAPABILITY,
  NODE_NAME_SYNC_CAPABILITY,
  SESSION_ACTIVITY_CAPABILITY,
  SESSION_CONFIG_CAPABILITY,
  SESSION_RETENTION_CAPABILITY,
  OUTBOX_ACK_CAPABILITY,
];
