import {
  AGENT_KINDS_CAPABILITY,
  AGENT_IDENTITY_CAPABILITY,
  HOST_URL_SYNC_CAPABILITY,
  MANAGED_WORKTREES_CAPABILITY,
  NODE_NAME_SYNC_CAPABILITY,
  OUTBOX_ACK_CAPABILITY,
  PORTABLE_WORKTREE_RESULTS_CAPABILITY,
  SELF_UPDATE_CAPABILITY,
  SESSION_ACTIVITY_CAPABILITY,
  SESSION_CONFIG_CAPABILITY,
  SESSION_RETENTION_CAPABILITY,
} from "@fleet/protocol";

export const NODE_CAPABILITIES = [
  AGENT_KINDS_CAPABILITY,
  MANAGED_WORKTREES_CAPABILITY,
  PORTABLE_WORKTREE_RESULTS_CAPABILITY,
  "copilot-acp",
  "host-yolo",
  HOST_URL_SYNC_CAPABILITY,
  SELF_UPDATE_CAPABILITY,
  NODE_NAME_SYNC_CAPABILITY,
  AGENT_IDENTITY_CAPABILITY,
  SESSION_ACTIVITY_CAPABILITY,
  SESSION_CONFIG_CAPABILITY,
  SESSION_RETENTION_CAPABILITY,
  OUTBOX_ACK_CAPABILITY,
];
